"""newspost

Revision ID: 55b585ac242d
Revises: 34f2334e9939
Create Date: 2021-04-17 20:31:18.918733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b585ac242d'
down_revision = '34f2334e9939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posttitle', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_post_timestamp'), 'news_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_post_timestamp'), table_name='news_post')
    op.drop_table('news_post')
    # ### end Alembic commands ###
